name: 'Discord Webhook Upload'
description: 'Send a message to discord webhook on a commit'
branding:
  icon: 'cast'
  color: 'blue'
inputs:
  url:
    description: 'Webhook URL'
    required: true
    default: ''
  username:
    description: 'Webhook username'
    required: false
    default: 'Username'
  avatar:
    description: 'Avatar URL'
    required: false
    default: ''
  file:
    description: 'File to send'
    required: false
    default: ''
  message:
    description: 'Message to send'
    required: true
    default: |
      ## Message header (change `message_header`) [**`#${{ github.run_number }}`**](<https://github.com/amblelabs/ait/actions/runs/${{ github.run_id }}>)
  msg_author:
    description: 'Author format'
    required: false
    default: '[${authorName}](<${authorUrl}>)'
  msg_author_separator:
    description: 'Author separator'
    required: false
    default: ' & '
  msg_commit:
    description: 'Per-commit message'
    required: false
    default: '- :sparkles: [${commitMessage}](<${commitUrl}>) by ${authors}'
  msg_commit_desc:
    description: 'Per-commit message description'
    required: false
    default: '-# > ${message}'
runs:
  using: 'node24'
  main: 'dist/index.js'
