name: 'Discord Webhook Upload'
description: 'Send a file to discord webhook'
inputs:
  url: # id of input
    description: 'Webhook url'
    required: true
    default: ''
  username:
    description: 'Webhook username'
    required: false
    default: 'Username'
  avatar:
    description: 'Avatar url'
    required: false
    default: ''
  file:
    description: 'File to send'
    required: true
    default: ''
  message:
    description: 'Message to send'
    required: false
    default: |
      New dev build:
      %COMMITS%
  commit:
    description: 'Per-commit message'
    required: false
    default: '> [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
  link:
    description: 'Link message'
    required: false
    default: 'Get it [here](%URL%)'
runs:
  using: 'node20'
  main: 'dist/index.js'
