name: 'Discord Webhook Upload'
description: 'Send a message to discord webhook on a commit'
icon: 'cast'
color: 'blue'
inputs:
  url: # id of input
    description: 'Webhook URL'
    required: true
    default: ''
  username:
    description: 'Webhook username'
    required: false
    default: 'Username'
  avatar:
    description: 'Avatar URL'
    required: false
    default: ''
  file:
    description: 'File to send'
    required: false
    default: ''
  mode:
    description: 'Action mode: currently only supports "commit"'
    required: false
    default: 'commit'
  message_header:
    description: 'Message to send'
    required: true
    default: |
      New dev build:
  message_commit:
    description: 'Per-commit message'
    required: false
    default: '> [${commitMessage}](<${commitUrl}>) by [${authorName}](<${authorUrl}>)'
runs:
  using: 'node20'
  main: 'dist/index.js'
