name: 'Discord Webhook Upload'
description: 'Send a file to discord webhook'
inputs:
  url: # id of input
    description: 'Webhook URL'
    required: true
    default: ''
  username:
    description: 'Webhook username'
    required: false
    default: 'Username'
  avatar:
    description: 'Avatar URL'
    required: false
    default: ''
  file:
    description: 'File to send'
    required: true
    default: ''
  message_header:
    description: 'Message to send'
    required: true
    default: |
      New dev build:
  message_commit:
    description: 'Per-commit message'
    required: false
    default: '> [${commitMessage}](<${commitUrl}>) by [${authorName}](<${authorUrl}>)'
runs:
  using: 'node20'
  main: 'dist/index.js'
